routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('/notes', 'NotesController');
Route::get('/notes/{note_id}/share', 'NotesController@shareSelect')->name('notes.share');
Route::post('/notes/{note_id}/share', 'NotesController@share')->name('notes.share.add');
Route::get('/notes/{note_id}/share/{user_id}/delete', 'NotesController@shareDelete')->name('notes.share.delete');
Route::get('/notes/shared/view', 'NotesController@displayShared')->name('notes.shared.display');

Route::get('/home', 'HomeController@index')->name('home');

app/Notes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notes extends Model
{
    const READ = 1;
    const UPDATE = 2;
    const DELETE = 3;

    const LVLS = [
        self::READ => "READ",
        self::UPDATE => "UPDATE",
        self::DELETE => "ADMIN",
    ];

    protected $table = 'notes';

    protected $fillable = [
        'title',
        'content',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'shared_notes', 'note_id', 'user_id')->withPivot('access_lvl');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function sharedNotes()
    {
        return $this->belongsToMany(Notes::class, 'shared_notes', 'user_id', 'note_id')->withPivot('access_lvl');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function notes()
    {
        return $this->hasMany(Notes::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NotesRequest;
use App\Notes;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NotesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notes = Auth::user()->notes()->get();

        return view('user.notes.index')->withData($notes);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.notes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(NotesRequest $request)
    {
        Auth::user()->notes()->create($request->all());

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd(Auth::user()->notes()->sharedNotes()-get());
        $notes = Auth::user()->sharedNotes()->find($id);

        if (empty($note))
            $notes = Auth::user()->notes()->findOrFail($id);

//        $notes = Auth::user()->notes()->findOrFail($id);
        $noteUsers = $notes->users()->get();
        $users = User::get();
        $access_lvls = Notes::LVLS;

        return view('user.notes.show')
                    ->withId($id)
                    ->withData($notes)
                    ->withUsers($users)
                    ->withNoteUsers($noteUsers)
                    ->withLvls($access_lvls);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Auth::user()->sharedNotes()->find($id);

        if (empty($note))
            Auth::user()->notes()->findOrFail($id);

        $note = Notes::where('id', $id)->get();

        return view('user.notes.edit')
            ->withFormData($note);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $note = Auth::user()->sharedNotes()->find($id);

        if (empty($note))
            $note = Auth::user()->notes()->findOrFail($id);

        $note->delete();
        return redirect()->back();
    }


    /**
     * Share the note Function
     *
     * @param $note_id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function share($note_id, Request $request)
    {
        $user_id = $request->user_id;
        $access_lvl = $request->access_lvl;

        $note = Auth::user()->notes()->findOrFail($note_id);

        User::findOrFail($user_id);

        $note->users()->attach($user_id);

        $user = $note->users()->find($user_id);

        $user->pivot->access_lvl = $access_lvl;

        $user->pivot->save();

        return redirect()->back();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function displayShared()
    {
        $notes = Auth::user()->sharedNotes()->get();

        dd(Auth::user()->sharedNotes()->get());

        return view('user.notes.shared')->withData($notes);
    }

    /**
     * Delete User From Shared
     *
     * @param $note_id
     * @param $user_id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function shareDelete($note_id, $user_id)
    {
        $note = Auth::user()->notes()->findOrFail($note_id);


        $note->users()->detach($user_id);
        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/notes/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form id="create_note_form" action="{{ route('notes.store') }}" method="POST">
            {!! csrf_field() !!}

            {{-- Title --}}
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" class="form-control"/>
                <span class="help-block error-message"></span>
            </div>

            {{-- Content --}}
            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content" name="content" class="form-control"></textarea>
                <span class="help-block error-message"></span>
            </div>

            <button type="submit">
                Save
            </button>

        </form>
    </div>
@stop

@section('js')
@stop

@section('css')
@stop

resources/views/user/notes/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form id="create_note_form" action="" method="POST">
            {!! csrf_field() !!}

            {{-- Title --}}
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ $formData->title }}"/>
                <span class="help-block error-message"></span>
            </div>

            {{-- Content --}}
            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content" name="content" class="form-control">
                    {{ $formData->content }}
                </textarea>
                <span class="help-block error-message"></span>
            </div>

            <button type="submit">
                Save
            </button>

        </form>
    </div>
@stop

@section('js')
@stop

@section('css')
@stop

resources/views/user/notes/index.blade.php
@extends('layouts.app')

@section('content')
    <div id="archive-page" class="container">

        <form action="" method="GET" class="form-inline mb-2">
            <div class="form-group col-12">
                <input type="text" class="form-control mb-3" id="search" placeholder="Search for a log" name="search">
                <button type="submit" class="btn btn-primary mb-3">Search</button>
            </div>

        </form>

        <div id="notes" class="row">
            @foreach($data as $value)
                <div class="notes-wrap col-6 col-md-4">

                    <div class="card-header" id="heading">
                        <h5 class="mb-0">
                            {{ $value->title }}
                        </h5>
                        <p>
                            {{ $value->content }}
                        </p>
                    </div>

                </div>
            @endforeach

        </div>
    </div>
@stop


@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('js/archive.js') }}"></script>
@stop

resources/views/user/notes/shared.blade.php
@extends('layouts.app')

@section('content')
    <div id="archive-page" class="container">

        <form action="" method="GET" class="form-inline mb-2">
            <div class="form-group col-12">
                <input type="text" class="form-control mb-3" id="search" placeholder="Search for a log" name="search">
                <button type="submit" class="btn btn-primary mb-3">Search</button>
            </div>

        </form>

        <div id="notes" class="row">
            <table class="notes-wrap col-6 col-md-4">

                <thead class="card-header" id="heading">

                </thead>
                <tbody>
                @foreach($data as $value)

                    <tr class="mb-0">
                        <td>
                            <h5>
                                {{ $value->title }}
                            </h5>
                            <p>
                                {{ $value->content }}
                            </p>
                        </td>
                    </tr>

                @endforeach
                </tbody>

            </table>

        </div>
    </div>
@stop


@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('js/archive.js') }}"></script>
@stop

resources/views/user/notes/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">

            <div class="col-12">
                <h1> {{$data->title}} </h1>
            </div>

            <div class="col-12">
                <p>
                    {{$data->content}}
                </p>
            </div>

        </div>

        <div class="row">

            <form class="col-12" method="POST" action="{{ route('notes.share.add', $id) }}">

                {!! csrf_field() !!}

                <select name="user_id" class="col-12 col-md-3">
                    @foreach($users as $user)
                        <option value="{{ $user->id }}"> {{ $user->name }} </option>
                    @endforeach
                </select>

                <select name="access_lvl" class="col-12 col-md-3">
                    @foreach($lvls as $key => $lvl)
                        <option value="{{ $key }}"> {{ $lvl }} </option>
                    @endforeach

                </select>
                <button class="col-12 col-md-3 btn" type="submit">
                    add
                </button>
            </form>
            <table class="col-12 table">
                <thead>
                    <td>User</td>
                    <td>Role</td>
                </thead>

                <tbody>
                    @foreach($noteUsers as $noteUser)
                        <tr>
                            <td>{{ $noteUser->name }}</td>

                            <td>{{ \App\Notes::LVLS[$noteUser->pivot->access_lvl] }}</td>

                            <td>
                                <a href="{{route('notes.share.delete', [$id ,$noteUser->id] )}}">x</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('js')
@stop

@section('css')
@stop

resources/views/user/share/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form id="create_note_form" action="{{ route('notes.share') }}" method="POST">
            {!! csrf_field() !!}

            {{-- Title --}}
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" class="form-control"/>
                <span class="help-block error-message"></span>
            </div>

            {{-- Content --}}
            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content" name="content" class="form-control"></textarea>
                <span class="help-block error-message"></span>
            </div>

            <button type="submit">
                Save
            </button>

        </form>
    </div>
@stop

@section('js')
@stop

@section('css')
@stop